---
title: ClearHead Architecture
---
flowchart BT
    user --uses--->clearhead.nvim
    clearhead.nvim --leverages--->clearhead-cli
    clearhead.nvim --leverages--->clearhead-LSP
    clearhead.nvim --leverages--->clearhead-graph
    clearhead-cli --leverages--->clearhead-core
    clearhead-LSP --leverages--->clearhead-core
    clearhead-graph --leverages--->clearhead-core
    clearhead-core --follows--->clearhead-specs
    clearhead-specs --follows--->action-ontology
