---
title: ClearHead Data Model
---
flowchart TD
    user --uses--->clearhead.nvim
    clearhead.nvim --edits--->workspace-files
    clearhead-cli --edits--->workspace-files
    clearhead-LSP --edits--->workspace-files
    clearhead-graph --reads--->workspace-files
    vdir--syncs--->workspace-files
    syncthing--syncs--->workspace-files
    git--syncs--->workspace-files
    vdir--communicates-with--->caldav-server
    workspace-files--conform--->clearhead-specs
